"""Embed VFX spritesheet JSON manifests and PNG data URIs for file:// testing."""

from __future__ import annotations

import base64
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST_OUTPUT = ROOT / "data" / "vfx" / "spritesheetManifests.js"
TEXTURE_OUTPUT = ROOT / "data" / "vfx" / "spritesheetTextures.js"

MANIFEST_PATHS = [
    "assets/effects/cast/psionic_cast_mind_focus_hex.json",
    "assets/effects/projectiles/mind_pressure_arc/mind_pressure_projectile.json",
    "assets/effects/impact/mind_ring_burst/mind_ring_burst.json",
]


def image_key_for_manifest(relative_manifest_path: str, manifest: dict) -> str:
    manifest_dir = Path(relative_manifest_path).parent.as_posix()
    image_name = manifest["meta"]["image"]
    return f"{manifest_dir}/{image_name}"


def to_data_uri(image_path: Path) -> str:
    payload = base64.standard_b64encode(image_path.read_bytes()).decode("ascii")
    return f"data:image/png;base64,{payload}"


def main() -> None:
    manifests = {}
    textures = {}

    for relative_path in MANIFEST_PATHS:
        json_path = ROOT / Path(relative_path)

        if not json_path.exists():
            raise SystemExit(f"Missing manifest: {json_path}")

        manifest = json.loads(json_path.read_text(encoding="utf-8"))
        manifests[relative_path] = manifest

        image_key = image_key_for_manifest(relative_path, manifest)
        image_path = ROOT / Path(image_key)

        if not image_path.exists():
            raise SystemExit(f"Missing spritesheet image: {image_path}")

        textures[image_key] = to_data_uri(image_path)

    manifest_payload = json.dumps(manifests, indent=2, ensure_ascii=False)
    MANIFEST_OUTPUT.write_text(
        "/* Auto-generated by tools/sync_vfx_manifests_js.py — do not edit by hand. */\n"
        f"const VFX_SPRITESHEET_MANIFESTS = {manifest_payload};\n",
        encoding="utf-8",
    )

    texture_payload = json.dumps(textures, ensure_ascii=False)
    TEXTURE_OUTPUT.write_text(
        "/* Auto-generated by tools/sync_vfx_manifests_js.py — do not edit by hand. */\n"
        f"const VFX_SPRITESHEET_TEXTURE_DATA = {texture_payload};\n",
        encoding="utf-8",
    )

    texture_size_kb = TEXTURE_OUTPUT.stat().st_size / 1024

    print(f"Synced {len(manifests)} manifest(s) -> {MANIFEST_OUTPUT.relative_to(ROOT)}")
    print(
        f"Synced {len(textures)} texture(s) -> {TEXTURE_OUTPUT.relative_to(ROOT)} "
        f"({texture_size_kb:.0f} KB)"
    )


if __name__ == "__main__":
    main()
