"""Embed VFX spritesheet JSON manifests AND PNG textures for file:// testing.

Why textures must be embedded (not just manifests):

Chromium/Firefox treat every file:// resource as a unique, opaque security origin
(CVE-2019-11730). This blocks more than fetch()/XHR for local JSON — it ALSO taints
any <img> loaded from a sibling file:// PNG the moment it is uploaded to WebGL via
texImage2D ("... cross-origin data, and may not be loaded"), even though the same
<img> displays fine as a normal DOM element. There is no way around this for
file:// except embedding the pixel data as a data: URI (which is same-origin,
since it carries no distinct origin at all) or serving the page over http(s).

So BOTH tiers are embedded here:
  * manifests — JSON, embedded because fetch()/XHR for local JSON is blocked.
  * textures  — PNG pixel data, embedded (as lossless WebP, ~5-20x smaller than
    PNG for these sheets — mostly flat color / transparency) because WebGL would
    otherwise refuse to use them as textures under file://.

The on-disk PNGs are left untouched and are still what gets used when the game is
served over http(s) (see assetManager.js resolveVfxImageSource / loadVfxManifest,
which prefer fetch()/plain URLs whenever not on file://).

Run:  py tools/sync_vfx_manifests_js.py

(The original pilot sheets — psionic_cast_mind_focus_hex, mind_pressure_arc,
mind_ring_burst — have been removed from the project; the 30 per-school sheets in
data/vfx/schoolVfxAssets.js / VFX_SCHOOL_SHEET_MANIFESTS replace them.)
"""

from __future__ import annotations

import base64
import io
import json
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
MANIFEST_OUTPUT = ROOT / "data" / "vfx" / "spritesheetManifests.js"
TEXTURE_OUTPUT = ROOT / "data" / "vfx" / "spritesheetTextures.js"

MANIFEST_GLOBS = [
    "assets/effects/cast/*.json",
    "assets/effects/impact/*.json",
    "assets/effects/projectiles/Beam/*.json",
    "assets/effects/projectiles/Schnitt/*.json",
    "assets/effects/projectiles/Explosion/*.json",
]


def discover_manifest_paths() -> list[str]:
    paths = []
    for pattern in MANIFEST_GLOBS:
        for match in sorted(ROOT.glob(pattern)):
            paths.append(match.relative_to(ROOT).as_posix())
    return paths


def image_key_for_manifest(relative_manifest_path: str, manifest: dict) -> str:
    manifest_dir = Path(relative_manifest_path).parent.as_posix()
    image_name = manifest["meta"]["image"]
    return f"{manifest_dir}/{image_name}"


def to_webp_data_uri(image_path: Path) -> str:
    im = Image.open(image_path).convert("RGBA")
    buf = io.BytesIO()
    im.save(buf, "WEBP", lossless=True)
    payload = base64.standard_b64encode(buf.getvalue()).decode("ascii")
    return f"data:image/webp;base64,{payload}"


def main() -> None:
    manifests = {}
    textures = {}

    manifest_paths = discover_manifest_paths()

    for relative_path in manifest_paths:
        json_path = ROOT / Path(relative_path)
        manifest = json.loads(json_path.read_text(encoding="utf-8"))
        manifests[relative_path] = manifest

        image_key = image_key_for_manifest(relative_path, manifest)
        image_path = ROOT / Path(image_key)

        if not image_path.exists():
            raise SystemExit(f"Missing spritesheet image: {image_path}")

        textures[image_key] = to_webp_data_uri(image_path)

    manifest_payload = json.dumps(manifests, indent=2, ensure_ascii=False)
    MANIFEST_OUTPUT.write_text(
        "/* Auto-generated by tools/sync_vfx_manifests_js.py — do not edit by hand. */\n"
        f"const VFX_SPRITESHEET_MANIFESTS = {manifest_payload};\n",
        encoding="utf-8",
    )

    texture_payload = json.dumps(textures, ensure_ascii=False)
    TEXTURE_OUTPUT.write_text(
        "/* Auto-generated by tools/sync_vfx_manifests_js.py — do not edit by hand. */\n"
        "/* Lossless WebP data URIs (see module docstring for why). */\n"
        f"const VFX_SPRITESHEET_TEXTURE_DATA = {texture_payload};\n",
        encoding="utf-8",
    )

    texture_size_kb = TEXTURE_OUTPUT.stat().st_size / 1024

    print(
        f"Synced {len(manifests)} manifest(s) -> {MANIFEST_OUTPUT.relative_to(ROOT)}"
    )
    print(
        f"Synced {len(textures)} texture(s) -> {TEXTURE_OUTPUT.relative_to(ROOT)} "
        f"({texture_size_kb:.0f} KB)"
    )


if __name__ == "__main__":
    main()
